### DISCUSSION TITLE
trying to handle the postgresql.conf from the host fails

### DISCUSSION THREAD

**Discussion by BigBoulard** [kartoza/docker-postgis#467] [Q&A] [answered]
Hi guys,

I'm trying to add some configuration options in `postgresql.conf`, so I just tried to bind mount  a copy of the one in the image at this location `/etc/postgresql/16/main/postgresql.conf` and add the options

```yml
postgres:
    image: kartoza/postgis:16-3.4
    hostname: postgres
    ports:
      - 5432:5432
    networks:
      - postgres-net
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASS=${PGPASSWORD}
    volumes:
      - postgres-vol:/var/lib/postgresql/data
      - ./pg/conf/postgresql.conf:/etc/postgresql/16/main/postgresql.conf <------------- BREAK THE SERVICE
```

when I start the service, I get this error in the container:

```sh
2024-03-05 19:38:27 Creating /settings directory
2024-03-05 19:38:27 Creating /docker-entrypoint.initdb.d directory
2024-03-05 19:38:27 sed: cannot rename /etc/postgresql/16/main/sedlDyNIm: Device or resource busy
```

**Comment by BigBoulard** [comment, marked as answer]
I just saw a previous question just after posting. Hence, I understand that extra configuration (or I assume overrides ) should be written in an `extra.conf` file bind mounted like below:

```yml
postgres:
    image: kartoza/postgis:16-3.4
    hostname: postgres
    ports:
      - 5432:5432
    networks:
      - postgres-net
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASS=${PGPASSWORD}
    volumes:
      - postgres-vol:/var/lib/postgresql/data
      - ./pg/conf/extra.conf:/settings/extra.conf
      
volumes:
  postgres-vol:
```

Best
