### ISSUE TITLE
Cant access postgis from another container running SQLAlchemy. 

### ISSUE THREAD

**Issue by archienorman11** [kartoza/docker-postgis#101]
Massively appreciated if someone can help out here:

I have a container running Flask, no issues:
```
api:
    restart: always
    build:
      context: .
      dockerfile: ./build/api/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgis
    command: bash -c "python3 /project/manage.py runserver --host=0.0.0.0"
```

I am running postgis like so:

```
postgis:
    image: kartoza/postgis:9.6-2.4
    ports:
      - 5432:5432
    volumes:
      - './build/db:/var/lib/postgresql'
    environment:
      - POSTGRES_DB=***
      - POSTGRES_USER=***
      - POSTGRES_PASS=***
      - ALLOW_IP_RANGE=0.0.0.0/0
    restart: unless-stopped
    command: sh -c "echo \"host all all 0.0.0.0/0 md5\" >> /etc/postgresql/9.4/main/pg_hba.conf && /start-postgis.sh"
```

Accessing postgis from my host works fine:

`$ psql -h 0.0.0.0 -U *** -p 5432 -l`

However, when I try to connect via my `api` container, I get the following error:

```sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
    Is the server running on host "127.0.0.1" and accepting
    TCP/IP connections on port 5432?
```

I connect from within my `api` container like so:

`postgres://***:***@postgis:5432/***`

Is there any reason why postgis is not available from other containers, but does work when accessing from the host? 

Thanks very much. 

Update: the `postgis` container is reachable from the `api` container. 

`docker-compose exec api bash -c "ping postgis"`
