### ISSUE TITLE
Connect to postgres when using django

### ISSUE THREAD

**Issue by koffisani** [kartoza/docker-postgis#124]
Hi,
I'm using this image for PostGIS, and facing issues to set correctly connection to Postgres database. 

Refering to [a docs about connecting to postgres](https://www.hackzine.org/postgis-on-gitlab-ci.html), I use this 

```
DATABASE_URL:` `"postgres://postgres:@kartoza_postgis/$POSTGRES_DB"
```
But I can't get it working. Can I have a little help ?

**Comment by NyakudyaA** [comment]
Hi @koffisani When you run the database what credentials are you using to initialise the database

Please look at the following https://stackoverflow.com/questions/30044904/how-should-i-set-my-database-url

**Comment by koffisani** [comment]
Hi @NyakudyaA, my CI config on gitlab looks like this
```yml
image: python:latest

services:
  - kartoza/postgis:11.0-2.5

variables:
  POSTGRES_DB: ci
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""

cache:
  paths:
  - ~/.cache/pip/

before_script:
  - python -V
  - wget https://download.osgeo.org/geos/geos-3.7.1.tar.bz2
  - tar xjf geos-3.7.1.tar.bz2
  - cd geos-3.7.1
  - ./configure
  - make
  - make install
  - wget https://download.osgeo.org/proj/proj-5.2.0.tar.gz
  - wget https://download.osgeo.org/proj/proj-datumgrid-1.8.tar.gz
  - tar xzf proj-5.2.0.tar.gz
  - cd proj-5.2.0/nad
  - tar xzf ../../proj-datumgrid-1.8.tar.gz
  - cd ..
  - ./configure
  - make
  - make install
  - cd ..
  - wget https://download.osgeo.org/gdal/2.4.1/gdal-2.4.1.tar.gz
  - tar xzf gdal-2.4.1.tar.gz
  - ls -al
  - cd gdal-2.4.1
  - ./configure
  - make
  - make install
  - cd ..
  - cd ..
  - pwd
  - ls -al
  - ln -s /usr/lib/libgdal.so /usr/lib/libgdal.so.1
  - /sbin/ldconfig
  - pip install -r requirements.txt

test:
  variables:
    DATABASE_URL: "postgres://postgres:@kartoza_postgis/$POSTGRES_DB"
  script:
- python manage.py test --settings cadastre.ci
```
