### ISSUE TITLE
Multiple databases using POSTGRES_DB with docker-compose

### ISSUE THREAD

**Issue by mmmmmrob** [kartoza/docker-postgis#131]
Thanks for the image, really helpful. Currently using `kartoza/postgis:10.0-2.4`.

Specifying multiple databases in docker-compose.yml doesn't seem to work:

```
db:
    image: kartoza/postgis:10.0-2.4
    volumes:
      - ./_ignore.postgres-data/db:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: dbone,dbtwo
      POSTGRES_PASSWORD: foobarbaz
      POSTGRES_USER: dbuser
```

This results in a database called `dbone,dbtwo`.

```
db_1         | Check default db exists
db_1         | Create default db dbone,dbtwo
db_1         |                                  List of databases
db_1         |        Name       |  Owner   | Encoding | Collate |  Ctype  |   Access privileges
db_1         | ------------------+----------+----------+---------+---------+-----------------------
db_1         |  dbone,dbtwo      | dbuser   | UTF8     | C.UTF-8 | C.UTF-8 |
db_1         |  postgres         | postgres | UTF8     | C.UTF-8 | C.UTF-8 |
db_1         |  template0        | postgres | UTF8     | C.UTF-8 | C.UTF-8 | =c/postgres          +
db_1         |                   |          |          |         |         | postgres=CTc/postgres
db_1         |  template1        | postgres | UTF8     | C.UTF-8 | C.UTF-8 | =c/postgres          +
db_1         |                   |          |          |         |         | postgres=CTc/postgres
db_1         |  template_postgis | postgres | UTF8     | C.UTF-8 | C.UTF-8 |
db_1         | (5 rows)
```
