### ISSUE TITLE
psql: could not connect to server: No such file or directory

### ISSUE THREAD

**Issue by ChrisCWerner** [kartoza/docker-postgis#146]
Hello! Thanks for the postgis image!

I'm having problems to get the postgis database server running. I am using docker-compose which looks like this:

```YAML
# docker-compose.yml
version: "3.3"
services:
...
  database:
    image: kartoza/postgis:latest
    restart: always
    environment:
      - POSTGRES_PASS=password
      - POSTGRES_USER=postgres
      - POSTGRES_DBNAME=db1,db2,db3
    volumes:
      - $HOME/database/postgis:/var/lib/postgresql
    ports:
      - "5432:5432"
...
```

And when I run `docker-compose up database`, I meet the following error:

```
...
database     | Success. You can now start the database server using:
database     |
database     |     /usr/lib/postgresql/11/bin/pg_ctl -D /var/lib/postgresql/11/main -l logfile start
database     | Add rule to pg_hba: replication user
database     | Setup master database
database     | 2019-09-05 23:05:54.294 UTC [25] FATAL:  "min_wal_size" must be at least twice "wal_segment_size"
database     | 2019-09-05 23:05:54.295 UTC [25] LOG:  database system is shut down
database     | psql: could not connect to server: No such file or directory
database     |  Is the server running locally and accepting
database     |  connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
...
```
And even when i try to start the db server with that command it doesn't work.
Any ideas of why it is not working?

PS1: when I change the volumes to `$HOME/database/postgis:/var/lib/postgresql/data`, the server starts normally, but the previous data won't load after a `down`.

PS2: I tried to use the previous version of the postgis image (kartoza/postgis:9.6-2.4) with the same setup docker-compose stated upwards. The server started and the data persisted, but because I need to create multiple databases it got south quickly as it created a database named "db1,db2,db3".
