### ISSUE TITLE
Running SQL Scripts at Startup in Compose

### ISSUE THREAD

**Issue by ranchodeluxe** [kartoza/docker-postgis#150]
Hello,
Thanks for creating this Docker image. I'm following the instructions [Running SQL Scripts at Startup](https://github.com/kartoza/docker-postgis#running-sql-scripts-on-container-startup) except that I'm declaring these in the `docker-compose.yml` file.  The files are mounted correctly but I'm never seeing any logs for loading and the data is not loaded. Is there a trick to using the init data script in `docker-compose.yml`?

```yml
  db:
    container_name: universe-db
    image: kartoza/postgis:9.5-2.2
    environment:
      - POSTGRES_DBNAME=admin
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,ogr_fdw
    ports:
      - '5432:5432'
    volumes:
      - ./universe/admin/sql/admin.sql:/docker-entrypoint-initdb.d/admin.sql
```

```bash
$ docker exec -it universe-db bash
root@b77c240a36fb:/# ls docker-entrypoint-initdb.d/
admin.sql
```
