### ISSUE TITLE
Change port using env vars

### ISSUE THREAD

**Issue by felipe-pereira** [kartoza/docker-postgis#158]
Hi, I see there are some env vars like `POSTGRES_USER `and others, but I want to run the db in a port different that 5432 (that one is already taken by the real db, the one I need a different port for is to run integration tests).

I see 5432 is hardcoded in many places, but asking anyways in case there was a simple way of changing the port.

We have this, but need to change the ports:
```
dbtest:
    networks:
      - testnetwork
    image: kartoza/postgis:11.0-2.5
    restart: always
    environment:
      POSTGRES_PASSWORD: testpassword
      POSTGRES_USER: test
      POSTGRES_DB: gendesigntest
      POSTGRES_MULTIPLE_EXTENSIONS: postgis,hstore,postgis_topology,ogr_fdw
    ports:
      - "5432:5432"
```
