### ISSUE TITLE
database empty

### ISSUE THREAD

**Issue by vladimirovii** [kartoza/docker-postgis#203]
Not keep database data after docker down!

You write
> Note: We highly recommend that you use tagged versions because successive minor versions of PostgreSQL write their database clusters into different database directories - which will cause your database to appear to be empty if you are using persistent volumes for your database storage.

Config:
```
version: '3.4'

services:
  postgresql:
    container_name: ${CONTAINER_PREFIX}_postgresql
    image: kartoza/postgis:12.0
    volumes:
      - POSTGRES_DATA:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

volumes:
  POSTGRES_DATA:
    name: "${CONTAINER_PREFIX}_pg_data"
```
