### ISSUE TITLE
Updated image: kartoza/postgis:12.0 breaks database - Permission denied

### ISSUE THREAD

**Issue by L-U-C-K-Y** [kartoza/docker-postgis#210]
Hi all

Ouroboros picked up the latest image on the 12.0 tag and the container is running into the following error:

(I'm creating a new user on startup too)

```
creating directory /var/lib/postgresql/12/main ... Setup master database
Initializing Postgres Database at /var/lib/postgresql/12/main
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.


The database cluster will be initialized with locales
  COLLATE:  en_US.UTF-8
  CTYPE:    en_US.UTF-8
  MESSAGES: C
  MONETARY: C
  NUMERIC:  C
  TIME:     C
The default text search configuration will be set to "english".


Data page checksums are disabled.


initdb: error: could not create directory "/var/lib/postgresql/12/main": Permission denied
creating directory /var/lib/postgresql/12/main ... 
```

Is anyone also experiencing this problem?

My docker-compose:

```
services:
  postgres:
    image: kartoza/postgis:12.0
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql"
      - "postgres-backups:/backups"
    secrets:
      - "secret"
    environment:
      - "POSTGRES_USER=overwatch_testing"
      - "POSTGRES_PASS_FILE=/run/secrets/secret"
      - "POSTGRES_DB=db1,db2,db3"
      - "POSTGRES_MULTIPLE_EXTENSIONS=postgis"
    restart: always
    healthcheck:
      test: "exit 0"
```

**Comment by NyakudyaA** [comment]
hi @lucbas Let me take a quick look. The travis test passed right,

**Comment by NyakudyaA** [comment]
> hi @lucbas Let me take a quick look. The travis test passed right,

Hi @lucbas I have just tested quickly and it seems that it is fine with me.
![new-image](https://user-images.githubusercontent.com/2510900/75056054-dd454a00-54de-11ea-9315-e853e4187212.png)

![db-running](https://user-images.githubusercontent.com/2510900/75056140-0d8ce880-54df-11ea-91f7-ec1c9ac52bf1.png)

I, however,  think the issue could be because of the secrets. Can you use environment variables
so that we can confirm they are causing the issue? 

I tested with the docker-compose in the repo

**Comment by L-U-C-K-Y** [comment]
Just tried to remove the secret and deleted the bind database folder in the development environment, so essentially starting from scratch, but still the same error:

![image](https://user-images.githubusercontent.com/14868134/75056811-02828a00-54d8-11ea-8ead-aa72b213c442.png)

What id does the postgres user have?

`docker exec -it <postgres_container> id postgres`

**Comment by L-U-C-K-Y** [comment]
I just found out that I'm able to start the image if I change the bind mount inside the container.
Wheras I had to explicitly bind the volume to ` - "postgres:/var/lib/postgresql"`, I can start the container now with  `- "postgres:/var/lib/postgresql/data"`.

```
services:
  postgres:
    image: kartoza/postgis:12.0
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
      - "postgres-backups:/backups"
    secrets:
      - "secret"
    environment:
      - "POSTGRES_USER=overwatch_testing"
      - "POSTGRES_PASS_FILE=/run/secrets/secret"
      - "POSTGRES_DB=db1,db2,db3"
      - "POSTGRES_MULTIPLE_EXTENSIONS=postgis"
    restart: always
    healthcheck:
      test: "exit 0"
```

Can you please share your docker-compose file?

Edit:
I can start the server and the logs show that the predefined databases are created, but the bind directory is still empty.
