### ISSUE TITLE
docker cannot mount postgres data in new image 

### ISSUE THREAD

**Issue by rsurgiewicz** [kartoza/docker-postgis#215]
Hi,
I have a postgres (12.0) directory used with previous image `kartoza/postgis` (image ID `e23f3b73c5ed`) but today I tried to update a `kartoza/postgis:latest` but it refuses to use existing data directory and tries to create one from scratch.

Works as a charm with previous image release...

`Setup master database
Initializing Postgres Database at /var/lib/postgresql/12/main
....
initdb: error: could not create directory "/var/lib/postgresql/12": Permission denied
`

I guess the issue is conneted with `VOLUME` declaration in new (updated 5d ago) Dockerfile.

My currect docker-compose:
```
db:  
    image: kartoza/postgis  
    restart: always  
    container_name: db_prod  
    environment:  
      POSTGRES_USER: xxx  
      POSTGRES_PASS: xxx  
      POSTGRES_DBNAME: xxx  
    ports:  
      - "5432:5432"  
    volumes:  
      - ./postgres_data:/var/lib/postgresql  
```

When I comment-out volumes declaration in docker-compose seems to start fine.

Could You kindly advice me how to properly re-use existing data?
