### ISSUE TITLE
I always get a "database system was not properly shut down; automatic recovery in progress"

### ISSUE THREAD

**Issue by betolink** [kartoza/docker-postgis#235]
I tried using v12.0 and v12.1 and in both cases I cannot reuse the data directory after populating it. 
I'm getting this error after I CTRL+C a docker-compose stack. 

```bash
db_1        | psql: error: could not connect to server: FATAL:  the database system is starting up
db_1        | 2020-04-19 19:26:08.371 UTC [16] LOG:  database system was not properly shut down; automatic recovery in progress
db_1        | 2020-04-19 19:26:08.373 UTC [16] LOG:  redo starts at 0/327F4C8
db_1        | 2020-04-19 19:26:08.373 UTC [16] LOG:  invalid record length at 0/327F500: wanted 24, got 0
db_1        | 2020-04-19 19:26:08.373 UTC [16] LOG:  redo done at 0/327F4C8
```

```yaml
  db:
    image: kartoza/postgis:12.1
    stop_grace_period: 60s
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: gis
      WAL_SIZE: 128MB
      WAL_SEGSIZE: 32
      EXISTING_DATA_DIR: "true"
```
I'm not sure if the container recreates the directory because of this error or a missing flag maybe related to https://github.com/kartoza/docker-postgis/issues/226
