### ISSUE TITLE
[RFC] Cluster Upgrade helper

### ISSUE THREAD

**Issue by lucernae** [kartoza/docker-postgis#243]
I would like to add functionality to upgrade cluster from previous major version to current major version.

I imagine we can use a stateless container to perform the upgrade like this:

```yaml
services:
  pg-upgrade:
    image: kartoza/postgis:12
    entrypoint: ""
    command: "/scripts/cluster_upgrade.sh"
    volumes:
      - previous-data-dir:/var/lib/postgresql/11
      - previous-config-dir:/etc/postgresql/11
      - data-dir:/opt/data/upgraded
    environment:
      PGVERSIONOLD: "11"
      PGVERSIONNEW: "12"
      PGBINOLD: "/usr/lib/postgresql/11/bin"
      PGBINNEW: "/usr/lib/postgresql/12/bin"
      PGDATAOLD: "/var/lib/postgresql/11/main"
      PGDATANEW: "/opt/data/upgraded"
```

# Proposed implementations

We are going to use postgresql common upgrade procedure, which is using `pg_upgradecluster`.
The upgrade process is going to be wrapped in `/scripts/cluster_upgrade.sh`.
What the script will do:
1. Make sure that binaries of target old version and new version exists (using `apt install` at run time)
2. Avoid name clash of default cluster `main` by doing `pg_renamecluster`. This should be ok and stateless since the containers only modifies internal data.
3. Perform cluster upgrade into the target directory `PGDATANEW`. This directory should be mounted to a volume.

Output:
1. New postgresql cluster with targeted version in the new volume (without the conf data)

Extensibility:
Users might want to perform some extra initialization/post upgrade steps. We provide a file hook called `/upgrade.d/pre.sh` and `upgrade.d/post.sh` to put a script hook. `pre.sh` will be executed before the upgrade. `post.sh` will be executed after a successful upgrade. Upgrade error can be detected and handled directly from stdout logs.

CC @NyakudyaA
