### ISSUE TITLE
RAM exploding and not released again

### ISSUE THREAD

**Issue by nilsnolde** [kartoza/docker-postgis#253]
Hi,
I'm pretty sure this is not actually an issue with your image, but either the server or the PG config. I feel I might be helped quicker here though than SO, since you know all the details on the startup and default behavior of your image. Feel free to close though as off-topic.

I run a (fairly recent) release of the `12.0` branch with pretty much default config. Mainly there's 2 huge raster tables (swissalti and Copernicus EU DEM 1.1), each around 30-40 GB. An instance of [openelevationservice](https://github.com/GIScience/openelevationservice) is querying elevation data for maximum 100 points at a time. Those requests are very infrequent, and yet, the RAM usage just explodes in no time at a very unreasonable rate, and is never released. Here's the DataDog excerpt:
![image](https://user-images.githubusercontent.com/25637358/84564090-b6967200-ad60-11ea-95ce-22d3742e6b18.png)

I try to do this for an NGO, on whose servers I don't have sudo rights. I can't even really pull web server logs. However, I can (almost) guarantee that the amount of RAM is not correlated to any actual DB queries, since querying elevation for 100 points at a time is nothing and there's not more than 2 of such requests per hour on average. In "worst case" I'll ask them to `cron` a daily script to restart the docker container at 2 am CEST.

I tried researching but couldn't find much of help. Maybe anyone here has some lightning idea?

**Comment by nilsnolde** [comment]
Here's the docker-compose.yml:
```
version: '2.2'

volumes:
  postgis-data:

networks:
  openelevation:

services:
 openelevationservice:
  image: uaveditor/openelevationservice:0.2.2-uav
  volumes:
  - /var/scripts/openelevationservice/data:/deploy/app/tiles
  ports:
   - "***:5000"
  mem_limit: 28g
  depends_on:
    - db
  environment:
    - PGPASSWORD=****
  restart: unless-stopped
  networks:
    - openelevation
 db:
    image: kartoza/postgis:12.0
    volumes:
      - postgis-data:/var/lib/postgresql
      - /var/scripts/openelevationservice/data:/tiles
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=gis
      - POSTGRES_USER=***
      - POSTGRES_PASS=***
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,postgis_raster
    restart: unless-stopped
    healthcheck:
      test: "exit 0"
    networks: 
      - openelevation
```
