### ISSUE TITLE
Peer authentication failed for user "docker"

### ISSUE THREAD

**Issue by Arman92** [kartoza/docker-postgis#259]
I'm using the docker-compose and it's my ``docker-compose.yml`` file:

```
db:
  image: kartoza/postgis:9.6-2.4
  volumes:
    - ./pg/postgres_data:/var/lib/postgresql
    - ./pg/setup_data:/home/setup
  environment:
    - USERNAME=docker
    - PASS=docker

dbbackup:
  image: kartoza/pg-backup:9.6
  hostname: pg-backups
  volumes:
    - ./backups:/backups
  links:
    - db:db
  environment:
    - DUMPPREFIX=PG_YOURSITE
    # These are all defaults anyway, but setting explicitly in
    # case we ever want to ever use different credentials
    - POSTGRES_USER=docker
    - POSTGRES_PASS=docker
    - POSTGRES_PORT=5432
    - POSTGRES_HOST=db
    - POSTGRES_DBNAME=gis
```

When I run ``sudo docker exec -i -t ubuntu_db_1 /bin/bash`` and then ``psql -U docker db`` I get ``psql: FATAL:  Peer authentication failed for user "docker"`` Error! 

It seems the user is not created at all. 

I've tried different ENV variables (e.g. POSTGRES_USER, USERNAME) etc but no luck.

P.S the docker-compose.yml contents are borrowed from your other repo : https://github.com/kartoza/docker-pg-backup
