### ISSUE TITLE
Unable to connect to psql in bash script running in docker-entrypoint-initdb.d

### ISSUE THREAD

**Issue by kristofj-umd** [kartoza/docker-postgis#260]
I am trying to run a bash script at `docker-compose up --build` that adds a new role to the `POSTGRES_DBNAME` database. I am doing this in a bash script since I need to make use of environment variables specified in the `--env-file` I use with `docker-compose`.
Adding the script as specified here (https://github.com/kartoza/docker-postgis#running-sql-scripts-on-container-startup) seems to work fine.
However, when I try and connect like this: `psql ${POSTGRES_DBNAME} -U ${POSTGRES_USER} --set ON_ERROR_STOP=on` I get an error that it can't connect to psql:
> postgis_1    | psql: could not connect to server: Connection refused
postgis_1    |  Is the server running on host "postgis" (172.17.9.4) and accepting
postgis_1    |  TCP/IP connections on port 5432?

When I try and connect like you specify here https://github.com/kartoza/docker-postgis/blob/16feae35b55270c181e5925c8ca37e784c549edb/scripts/env-data.sh#L291
I get the following error:

> postgis_1    | psql: could not connect to server: Connection refused
postgis_1    |  Is the server running on host "localhost" (127.0.0.1) and accepting
postgis_1    |  TCP/IP connections on port 5432?
postgis_1    | could not connect to server: Cannot assign requested address
postgis_1    |  Is the server running on host "localhost" (::1) and accepting
postgis_1    |  TCP/IP connections on port 5432?

Please advise me on either the best way to add a new user to the database or connect to psql via a bash script. 
Thank you.

**Comment by NyakudyaA** [comment]
You need to connect using the full credentials ie psql- d gis -p 5432 -U docker -h localhost and also send the full logs when it starts

**Comment by kristofj-umd** [comment]
I did try and connect like this: `psql -d ${POSTGRES_DBNAME} -U ${POSTGRES_USER} -p 5432 -h localhost` and this is the first hundred or so lines of the log (note that I am using persistent storage so the DB would have been created on a previous aborted run):

> postgis_1    |
postgis_1    | ssl already configured
postgis_1    | we will setup pg_hba conf
postgis_1    | Add rule to pg_hba: replication user
postgis_1    | Setup master database
postgis_1    | Creating Wal archive directory at /opt/archivedir
postgis_1    | 2020-07-08 15:28:00.317 UTC [26] LOG:  database system was shut down at 2020-07-08 15:19:28 UTC
postgis_1    | 2020-07-08 15:28:00.319 UTC [26] LOG:  MultiXact member wraparound protections are now enabled
postgis_1    | 2020-07-08 15:28:00.323 UTC [32] LOG:  autovacuum launcher started
postgis_1    | 2020-07-08 15:28:00.323 UTC [19] LOG:  database system is ready to accept connections
postgis_1    |                                  List of databases
postgis_1    |        Name       |   Owner   | Encoding  | Collate | Ctype |   Access privileges
postgis_1    | ------------------+-----------+-----------+---------+-------+-----------------------
postgis_1    |  nra-dev          | nra_admin | UTF8      | C       | C     |
postgis_1    |  postgres         | postgres  | SQL_ASCII | C       | C     |
postgis_1    |  template0        | postgres  | SQL_ASCII | C       | C     | =c/postgres          +
postgis_1    |                   |           |           |         |       | postgres=CTc/postgres
postgis_1    |  template1        | postgres  | SQL_ASCII | C       | C     | =c/postgres          +
postgis_1    |                   |           |           |         |       | postgres=CTc/postgres
postgis_1    |  template_postgis | postgres  | UTF8      | C       | C     |
postgis_1    | (5 rows)
postgis_1    |
postgis_1    | postgres ready
postgis_1    | Postgis Already There
postgis_1    | HSTORE is only useful when you create the postgis database.
postgis_1    | TOPOLOGY is only useful when you create the postgis database.
postgis_1    | Setup postgres User:Password
postgis_1    | ALTER ROLE
postgis_1    | Check default db exists
postgis_1    | nra-dev db already exists
postgis_1    |                                  List of databases
postgis_1    |        Name       |   Owner   | Encoding  | Collate | Ctype |   Access privileges
postgis_1    | ------------------+-----------+-----------+---------+-------+-----------------------
postgis_1    |  nra-dev          | nra_admin | UTF8      | C       | C     |
postgis_1    |  postgres         | postgres  | SQL_ASCII | C       | C     |
postgis_1    |  template0        | postgres  | SQL_ASCII | C       | C     | =c/postgres          +
postgis_1    |                   |           |           |         |       | postgres=CTc/postgres
postgis_1    |  template1        | postgres  | SQL_ASCII | C       | C     | =c/postgres          +
postgis_1    |                   |           |           |         |       | postgres=CTc/postgres
postgis_1    |  template_postgis | postgres  | UTF8      | C       | C     |
postgis_1    | (5 rows)
postgis_1    |
postgis_1    | 2020-07-08 15:28:00.614 UTC [19] LOG:  received smart shutdown request
postgis_1    | 2020-07-08 15:28:00.615 UTC [32] LOG:  autovacuum launcher shutting down
postgis_1    | 2020-07-08 15:28:00.616 UTC [29] LOG:  shutting down
postgis_1    | 2020-07-08 15:28:00.629 UTC [19] LOG:  database system is shut down
postgis_1    |
postgis_1    | /docker-entrypoint.sh: running /docker-entrypoint-initdb.d/add_read_only_user.sh
postgis_1    | Creating read only user: read_only_user
postgis_1    | psql: could not connect to server: Connection refused
postgis_1    |  Is the server running on host "localhost" (127.0.0.1) and accepting
postgis_1    |  TCP/IP connections on port 5432?
postgis_1    | could not connect to server: Cannot assign requested address
postgis_1    |  Is the server running on host "localhost" (::1) and accepting
postgis_1    |  TCP/IP connections on port 5432?
postgis_1    |
postgis_1    | postgres conf already configured
postgis_1    | ssl already configured
postgis_1    | pg_hba  already configured
postgis_1    | Setup master database
postgis_1    | 2020-07-08 15:28:02.443 UTC [26] LOG:  database system was shut down at 2020-07-08 15:28:00 UTC
postgis_1    | 2020-07-08 15:28:02.444 UTC [27] postgres@postgres FATAL:  the database system is starting up
postgis_1    | psql: FATAL:  the database system is starting up
postgis_1    | 2020-07-08 15:28:02.448 UTC [26] LOG:  MultiXact member wraparound protections are now enabled
postgis_1    | 2020-07-08 15:28:02.450 UTC [15] LOG:  database system is ready to accept connections
postgis_1    | 2020-07-08 15:28:02.451 UTC [32] LOG:  autovacuum launcher started
postgis_1    |                                  List of databases
postgis_1    |        Name       |   Owner   | Encoding  | Collate | Ctype |   Access privileges
postgis_1    | ------------------+-----------+-----------+---------+-------+-----------------------
postgis_1    |  nra-dev          | nra_admin | UTF8      | C       | C     |
postgis_1    |  postgres         | postgres  | SQL_ASCII | C       | C     |
postgis_1    |  template0        | postgres  | SQL_ASCII | C       | C     | =c/postgres          +
postgis_1    |                   |           |           |         |       | postgres=CTc/postgres
postgis_1    |  template1        | postgres  | SQL_ASCII | C       | C     | =c/postgres          +
postgis_1    |                   |           |           |         |       | postgres=CTc/postgres
postgis_1    |  template_postgis | postgres  | UTF8      | C       | C     |
postgis_1    | (5 rows)
postgis_1    |
postgis_1    | postgres ready
postgis_1    | Postgis Already There
postgis_1    | HSTORE is only useful when you create the postgis database.
postgis_1    | TOPOLOGY is only useful when you create the postgis database.
postgis_1    | Setup postgres User:Password
postgis_1    | ALTER ROLE
postgis_1    | Check default db exists
postgis_1    | nra-dev db already exists

**Comment by lucernae** [comment]
Hi, I think you failed to connect because you didn't specify the password.
Our scripts works because the environment variable PGPASSWORD are set in the preparation phase `env-data.sh`

Can you try setting the variable PGPASSWORD, or just source `env-data.sh` like this before you use psql to connect:

```bash
source /scripts/env-data.sh
```

Depending on the version of the image, env-data.sh might be in `/scripts/env-data.sh` or `/env-data.sh`

**Comment by kristofj-umd** [comment]
I have `PGPASSWORD` set as an environment variable in an environment file passed during build:
```bash
docker-compose \
  --env-file test_data_local.env \
  build
```
I confirmed `PGPASSWORD` is available in the container by calling `printenv` in the bash script.

Calling psql like this (`psql -d ${POSTGRES_DBNAME} -U ${POSTGRES_USER} -p 5432 -h localhost --set ON_ERROR_STOP=on`) is not working. 
What is the correct way to connect to the database using a bash script during container initialization?

**Comment by kristofj-umd** [comment]
Should I run my psql query as you do here:
https://github.com/kartoza/docker-postgis/blob/18f99bc8d65bba72f4f5fe7f63d9e0fa179c73b2/scripts/setup-user.sh#L28
as the `postgres` system user?

**Comment by NyakudyaA** [comment]
> I have `PGPASSWORD` set as an environment variable in an environment file passed during build:
> 
> ```shell
> docker-compose \
>   --env-file test_data_local.env \
>   build
> ```
> 
> I confirmed `PGPASSWORD` is available in the container by calling `printenv` in the bash script.
> 
> Calling psql like this (`psql -d ${POSTGRES_DBNAME} -U ${POSTGRES_USER} -p 5432 -h localhost --set ON_ERROR_STOP=on`) is not working.
> What is the correct way to connect to the database using a bash script during container initialization?

Just set your env variable ln the script like
```
export PGPASSWORD="test"
```
 or run it as 
```
PGPASSWORD=${POSTGRES_PASS} psql ${db} -U ${POSTGRES_USER} -p 5432 -h localhost
```

**Comment by kristofj-umd** [comment]
Attempting @NyakudyaA 's suggestion above failed as before.
code snippet:
```bash
PGPASSWORD=${POSTGRES_PASS}
PSQL_RUN="psql -d ${POSTGRES_DBNAME} -U ${POSTGRES_USER} -p 5432 -h localhost --set ON_ERROR_STOP=on"
```
log:

> postgis_1    | /docker-entrypoint.sh: running /docker-entrypoint-initdb.d/add_read_only_user.sh
postgis_1    | Creating read only user: read_only_user
postgis_1    | psql: could not connect to server: Connection refused
postgis_1    |  Is the server running on host "localhost" (127.0.0.1) and accepting
postgis_1    |  TCP/IP connections on port 5432?
postgis_1    | could not connect to server: Cannot assign requested address
postgis_1    |  Is the server running on host "localhost" (::1) and accepting
postgis_1    |  TCP/IP connections on port 5432?


I tried testing out the `postgres` user method (ie. `su - postgres -c "psql postgres -c ...`) with a simple command and it failed. Here is the log output:

> postgis_1    | 2020-07-17 14:59:15.097 UTC [16] LOG:  received smart shutdown request
postgis_1    | 2020-07-17 14:59:15.097 UTC [25] LOG:  autovacuum launcher shutting down
postgis_1    | 2020-07-17 14:59:15.099 UTC [22] LOG:  shutting down
postgis_1    | 2020-07-17 14:59:15.112 UTC [16] LOG:  database system is shut down
postgis_1    |
postgis_1    | /docker-entrypoint.sh: running /docker-entrypoint-initdb.d/test_psql.sh
postgis_1    | psql: could not connect to server: No such file or directory
postgis_1    |  Is the server running locally and accepting
postgis_1    |  connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

That error makes me think the database is not up and running so of course it can't connect to it. Why is the database shutdown before hand? And how are scripts in `/docker-entrypoint-initdb.d` supposed to execute if the database is shutdown?

**Comment by kristofj-umd** [comment]
I also tried running these commands in a `.sql` script without the benefit of environment variables just for testing, and while it did not error out, it also seemed to do nothing. If I run the same `.sql` file after the containers are up and running using `exec psql`, then the query runs as expected.
Ideally, for deployment purposes I would like to be able to run these scripts during initialization. But until this can be fixed I will just run them manually afterwards on the running container.

**Comment by NyakudyaA** [comment]
@kristofj-umd there is something you are doing which is not right. Are you using docker volume ?.

I just tested this quickly and it works
![example-proble](https://user-images.githubusercontent.com/2510900/87805549-c1f42600-c855-11ea-92a6-2a2a20e7f493.png)

And here is it running
![Peek 2020-07-17 17-47](https://user-images.githubusercontent.com/2510900/87805581-d3d5c900-c855-11ea-96ef-4d1fa8b7c5db.gif)

If you still experience any problems and are interested in us helping you with your setup please consider https://github.com/kartoza/docker-postgis#support

**Comment by kristofj-umd** [comment]
I'm not sure what I'm doing wrong. Below is my docker-compose. It is essentially a postgis/geoserver arrangement.
```yaml
version: '3'
services:
  postgis:
    env_file:
      - ${ENV_FILE}
    # don't use container_name, too much trouble in docker-compose
    # container_name: ${PGHOST}
    image: kartoza/postgis:9.6-2.4
    environment:
      # map from Postgresql PG<FOO> names to POSTGRES_<FOO> the container uses
      # http://www.postgresql.org/docs/current/static/libpq-envars.html
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASS=${PGPASSWORD}
      - POSTGRES_DBNAME=${PGDATABASE}
      # - ALLOW_IP_RANGE=131.212.22.0/24
      # add to setup.sh explicitly - ALLOW_IP_RANGE=172.19.0.0/24
      # - ALLOW_IP_RANGE=172.0.0.0/8
    volumes:
      # persistent DB data on host
      - ${VOL_PGDATA}:/var/lib/postgresql
      # script to run after build
      - ./add_read_only_user.sh:/docker-entrypoint-initdb.d/add_read_only_user.sh
      # large GIS datasets on host - add these in secondary docker-compose file now
      # - ${VOL_nra_large_data}:/var/local/host_gisdata
      # adding custom configuration file
      # ref: https://stackoverflow.com/a/41912295
      # FIXME: use EXTRA_CONF instead?
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    # add commands to tune postgres DB for postgis
    # command: postgres -c shared_buffers=4000MB -c work_mem=1000MB -c maintenance_work_mem=2048MB
    #   -c wal_buffers=1MB -c random_page_cost=2 -c max_connections=1000 -c max_worker_processes=8
    #   -c max_parallel_workers_per_gather=8
    #X ports:
    #X   - "32786:5432"
    restart: unless-stopped

  postcache:
    env_file:
      - ${ENV_FILE}
    image: kartoza/postgis:9.6-2.4
    environment:
      - POSTGRES_USER=postcache
      - POSTGRES_PASS=Somethingabouth0rses
      - POSTGRES_DBNAME=postcache
    volumes:
      # persistent DB data on host
      - ${VOL_PGCACHE}:/var/lib/postgresql
    # ports:
    #   - "33333:5432"
    restart: unless-stopped

  geoserver:
    # don't use container_name, too much trouble in docker-compose
    # container_name: ${GSHOST}
    env_file:
      - ${ENV_FILE}
    image: kartoza/geoserver:2.16.1
    # image: kartoza/geoserver:2.15.2
    # image: kartoza/geoserver:2.13.0
    # build:
    #   # build from oscarfonts geoserver 2.13.3 directory
    #   context: ./docker-geoserver/2.16.1
    volumes:
      # persistent geoserver data on host
      - ${VOL_GSDATA}:${GEOSERVER_DATA_DIR}
      # store geowebcache on large disk
      - ${VOL_GSCACHE}:${GEOSERVER_DATA_DIR}/gwc
      # # persist use of postgresql container for cache management
      # - ./geowebcache-diskquota-jdbc.xml:${GEOSERVER_DATA_DIR}/gwc/geowebcache-diskquota-jdbc.xml
      # large GIS datasets on host - add these in secondary docker-compose file now
      # - ${VOL_nra_large_data}:/var/local/host_gisdata
      # geoserver extensions to be installed
      - ./geoserver-extensions:/var/local/geoserver-exts
    ports:
      - "${GSPORT_EXT}:8080"
    restart: unless-stopped
    depends_on:
      - postgis

  # This container just exits immediately, we'll run it manually later.
  # Defining it here gets us on the right internal network etc.
  importer:
    env_file:
      - ${ENV_FILE}
    build:
      context: ./import/import2geoserver
    # dummy command, we'll run the container manually later
    command: date
    volumes:
      - ${VOL_import_src}:/import_src
      - ${VOL_import_inputs}:/import_inputs
      - ${VOL_import_outputs}:/import_outputs
      - ${VOL_atlas_data_root}:/data
```
Could it possibly be due to my use of persistent volumes? In other words, when my entrypoint script is run, the database is already there and it shuts down before running the script?
