### ISSUE TITLE
ERROR:  failed to authenticate with backend using SCRAM

### ISSUE THREAD

**Issue by hyungmok** [kartoza/docker-postgis#277]
Hi,

My team was using the combination of bitnami / bitnami-docker-postgresql-repmgr and bitnami / bitnami-docker-pgpool, but we wanted to include pgRouting and made a workaround by updating kartoza / docker-postgis repo. I've updated kartoza / docker-postgis and successfully created Docker image/container. I thought it would work well with bitnami / bitnami-docker-pgpool but faced a problem and trying to find a way to get it sorted out. I got an error in the pgpool container as following:

```
2020-10-19 08:30:13: pid 135: ERROR:  failed to authenticate with backend using SCRAM
2020-10-19 08:30:13: pid 135: DETAIL:  valid password not found
```

Can anyone please advise me in which case that sort of error would happen? I appreciate your comments in advance.

Thanks!

FYI. You can have a look at the changes on the branch feature/repmgr in my repo https://github.com/hyungmoklee/docker-postgis.

**Comment by NyakudyaA** [comment]
> Hi,
> 
> My team was using the combination of bitnami / bitnami-docker-postgresql-repmgr and bitnami / bitnami-docker-pgpool, but we wanted to include pgRouting and made a workaround by updating kartoza / docker-postgis repo. I've updated kartoza / docker-postgis and successfully created Docker image/container. I thought it would work well with bitnami / bitnami-docker-pgpool but faced a problem and trying to find a way to get it sorted out. I got an error in the pgpool container as following:
> 
> ```
> 2020-10-19 08:30:13: pid 135: ERROR:  failed to authenticate with backend using SCRAM
> 2020-10-19 08:30:13: pid 135: DETAIL:  valid password not found
> ```
> 
> Can anyone please advise me in which case that sort of error would happen? I appreciate your comments in advance.
> 
> Thanks!
> 
> FYI. You can have a look at the changes on the branch feature/repmgr in my repo https://github.com/hyungmoklee/docker-postgis.

Can you please highlight the changes you have made. We cannot look at the whole repo. And what command did you use to startup the containers.

Since V13.0 the default authentification method is now `scram-sha-256` so if you using an existing data directory you will need to use the env variable `-e --auth="md5"`

**Comment by hyungmok** [comment]
@NyakudyaA Thanks for your answer. I'd like to stress that I used the bitnami-docker-pgpool and wanted to integrate it with docker-postgis. So I guess the issue might be associated with the bitnami-docker-pgpool.

FYI, I made changes in Dockerfile as following to include the repmgr thing:

```
RUN set -eux \
    && export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get -y --no-install-recommends install apt-transport-https \
    && sh -c 'echo "deb https://apt.2ndquadrant.com/ $(lsb_release -cs)-2ndquadrant main" > /etc/apt/sources.list.d/2ndquadrant.list' \
    && apt-get -y --no-install-recommends install curl ca-certificates \
    && curl https://apt.2ndquadrant.com/site/keys/9904CD4BD6BAF0C3.asc | apt-key add - \
    && apt-get update \
    && apt-get -y --no-install-recommends install postgresql-${POSTGRES_MAJOR_VERSION}-repmgr
```

Also, I checked the pool_passwd file in the pgpool docker, and the user credentials are in it as defined in the Dockerfile as following:

postgres:md532e12f215ba27cb750c9e093ce4b5127
custom:md5062eefea99d9edc2e03ace900e029735

FYI, attached the entire contents of the docker-compose.yml for postgres and pgpool.

```
version: "3"

services:
  pg-0:
    container_name: pg-0
    image: docker.io/hyeongmoklee/docker-postgis:1
    ports:
      - 5432
    volumes:
      - pg_0_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=password
      - POSTGRES_DB=tiot
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
      - --auth="md5"
  pg-1:
    container_name: pg-1
    image: docker.io/hyeongmoklee/docker-postgis:1
    ports:
      - 5432
    volumes:
      - pg_1_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=password
      - POSTGRES_DB=tiot
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
      - --auth="md5"
  pgpool:
    container_name: pgpool
    image: docker.io/bitnami/pgpool:4-debian-10
    ports:
      - 5432:5432
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432
      - PGPOOL_SR_CHECK_USER=postgres
      - PGPOOL_SR_CHECK_PASSWORD=password
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=password
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=password
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
      - PGPOOL_POSTGRES_CUSTOM_USERS=custom
      - PGPOOL_POSTGRES_CUSTOM_PASSWORDS=password
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_0_data:
    driver: local
  pg_1_data:
    driver: local
```
