### ISSUE TITLE
Tag 13-3.1 doesn't survive container recreate because waldir is missing.

### ISSUE THREAD

**Issue by lucernae** [kartoza/docker-postgis#321]
When the container is recreated, it complains that the `pg_wal` directory is missing.
It turns out that the `pg_wal` directory inside the `PGDATA` directory is only a link to whatever directory specified in `POSTGRES_INITDB_WALDIR`.
I was under the impression that this env `POSTGRES_INITDB_WALDIR` is only for initializations.
It currently failed upon recreate because `POSTGRES_INITDB_WALDIR` is outside the default persistent volume.
When the container is recreated, the `pg_wal` content is lost, which is very dangerous.

Furthermore, if I specified `POSTGRES_INITDB_WALDIR` into a directory inside the persistent volume, the container is failed to initialize, because in `setup-database.sh` after directory creation, we deleted using `rm -rf ${DATADIR}` which caused the initdb waldir to be deleted again. So the postgres init, it failed to find the initdb waldir.

@NyakudyaA do you have any suggestion to fix this?
Is it ok to just move the `rm -rf ${DATADIR}` up to delete the content before the initdb waldir creation?
From what I understand by default you want the initdb waldir to be outside the default volume. However if initdb waldir is not persisted, when containers are recreated the symlink will not find the directory.

**Comment by NyakudyaA** [comment]
@lucernae how do I test this, let me test this and revert back

**Comment by NyakudyaA** [comment]
@lucernae is this the same issue as #317

If so can you please pull and get the latest image

**Comment by NyakudyaA** [comment]
> When the container is recreated, it complains that the `pg_wal` directory is missing.
> It turns out that the `pg_wal` directory inside the `PGDATA` directory is only a link to whatever directory specified in `POSTGRES_INITDB_WALDIR`.
> I was under the impression that this env `POSTGRES_INITDB_WALDIR` is only for initializations.
> It currently failed upon recreate because `POSTGRES_INITDB_WALDIR` is outside the default persistent volume.
> When the container is recreated, the `pg_wal` content is lost, which is very dangerous.
> 
> Furthermore, if I specified `POSTGRES_INITDB_WALDIR` into a directory inside the persistent volume, the container is failed to initialize, because in `setup-database.sh` after directory creation, we deleted using `rm -rf ${DATADIR}` which caused the initdb waldir to be deleted again. So the postgres init, it failed to find the initdb waldir.
> 
> @NyakudyaA do you have any suggestion to fix this?
> Is it ok to just move the `rm -rf ${DATADIR}` up to delete the content before the initdb waldir creation?
> From what I understand by default you want the initdb waldir to be outside the default volume. However if initdb waldir is not persisted, when containers are recreated the symlink will not find the directory.

I could not replicate this issue @lucernae

**Comment by lucernae** [comment]
Ok. Let me test this again after repull.

**Comment by lucernae** [comment]
Still the same errors.

# First case (if we didn't set POSTGRES_INITDB_WALDIR)

This is a simplified version of how I usually deploy on prod.
I mount a persistent volume into `/opt/kartoza/postgis/data` and set `PGDATA=/opt/kartoza/postgis/data`.
Is it mandatory for me to also set `POSTGRES_INITDB_WALDIR` to a different persistent volume? Because I thought this env is for custom initialization (if you already have a waldir to import). CMIIW
The docker-compose recipe:

```yaml
# docker-compose build
version: '3.4'
volumes:
  dbbackups:
  postgis-data:

services:

  db:
    image: kartoza/postgis:13-3.1
    volumes:
      - postgis-data:/opt/kartoza/postgis/data
      - dbbackups:/backups
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      - PGDATA=/opt/kartoza/postgis/data
    ports:
      - 25432:5432
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=${POSTGRES_PASS} psql -h localhost -U docker -d gis -l"
```

Run it with `docker-compose up -d`.
First run will be successful. If you shell inside the container, you will see that `/opt/kartoza/postgis/data/pg_wal` is a symlink.
Delete the container using `docker-compose down` (this will delete only the container but not the volumes).
Run it again using `docker-compose up -d`. I expect this to run, but it failed because `/var/lib/postgresql/13/pg_waldir` was reset to empty. That means `POSTGRES_INITDB_WALDIR` is actually used by postgres not just in initialization phase, but throughout the lifecycle. If this is indeed true then we should change the env to just become `POSTGRES_WALDIR` then set the default to be within the default persisted volume.

# Second case (assuming that setting `POSTGRES_INITDB_WALDIR` is mandatory not just in initialization step)

If the waldir was meant to be persisted (not just from initialization phase), that means by default it has to stay within the default persisted volume. I emulate it by setting the environment variable (it needs to be implicitly defined by the entrypoint if user don't provide this. However I set this explicitly at the moment).

```yaml
# docker-compose build
version: '3.4'
volumes:
  dbbackups:
  postgis-data:

services:

  db:
    image: kartoza/postgis:13-3.1
    volumes:
      - postgis-data:/opt/kartoza/postgis/data
      - dbbackups:/backups
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      - PGDATA=/opt/kartoza/postgis/data
      - POSTGRES_INITDB_WALDIR=/opt/kartoza/postgis/data/pg_wal
    ports:
      - 25432:5432
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=${POSTGRES_PASS} psql -h localhost -U docker -d gis -l"
```

This recipe doesn't run the containers because of:
> Furthermore, if I specified POSTGRES_INITDB_WALDIR into a directory inside the persistent volume, the container is failed to initialize, because in setup-database.sh after directory creation, we deleted using rm -rf ${DATADIR} which caused the initdb waldir to be deleted again. So the `postgres init` command failed to find the initdb waldir.

I think, this second case here is definitely a bug. We should delete the DATADIR first then create the directory for datadir and waldir.
Meanwhile, the first case is just about convention. I don't know if `POSTGRES_INITDB_WALDIR` were supposed to be used as initialization only, or forever (as a way to specify the pg_wal location). For this one, I need your opinion.
