### ISSUE TITLE
Container not running CREATE EXTENSION POSTGIS;

### ISSUE THREAD

**Issue by codydaig** [kartoza/docker-postgis#326]
I have the following in my docker-compose.yml

```
  db:
    image: kartoza/postgis:13.0
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    restart: on-failure
    healthcheck:
      test: "exit 0"
```

However, once the container has been established, I have to go into the container, connect to the `postgres` database and run `CREATE EXTENSION postgis;` before I can use geometry data types. 

Any advice here? Thanks!
