### ISSUE TITLE
FATAL:  lock file "postmaster.pid" already exists

### ISSUE THREAD

**Issue by agatheLG123** [kartoza/docker-postgis#331]
Hi,
I tried to launch a `docker-compose up --build` in a server however I get the error : 
FATAL:  lock file "postmaster.pid" already exists
HINT: Is another postmaster (PID 90) running in data directory "/var/lib/postgresql/13/main"?

I have tried deleting container, image, volumes, I have tried the command `docker system prune --volumes` but I still get the same error... How is it possible ? I also tried changing volumes to named volumes but id di not changed anything.
My current docker-compose.yml looks like this: 
```
[...]
  postgres_db:
    image:  kartoza/postgis
    env_file:
      - ./.env
    volumes:
      # - ./data/db:/var/lib/postgresql/data
      - postgre_data:/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  volumes:
    minio_data:
    postgre_data :
```
I can't find the postmaster.pid file nor kill the process because the container is directly exiting with code 1. I read loads of forum but can't seem to find what's wrong... If you have any idea, I would be really grateful ! Thanks
