### ISSUE TITLE
Errors while downloading kartoza/postgis volume from FileZilla

### ISSUE THREAD

**Issue by fedegibut** [kartoza/docker-postgis#379]
Good morning,
I am using [this image](https://hub.docker.com/layers/postgis/kartoza/postgis/14-3.2--v2022.05.09/images/sha256-4e3e4f9edcc9c37bc83f2b3e8c27f2153716fdfd558a9e122b6c0428e0ce8844) of yours and I have the following problem.
I cannot copy the files on the server locally. 
```
Error: Directory/home/ubuntu/ServerDockerJava01/volumes/data-postgresql/14/main: permission denied
Error: Failed to retrieve directory listing
```
I get this error when I copy files from FileZilla to my local computer and after the database is running and inside the data-postgresql folder, Docker has added the '14' folder.
How do you advise me to proceed?
Is my code correct?
Do you have any suggestions to improve it?
I would like to save the database by backing up /volumes/data-postgresql without being forced to use pgAdmin.
Best regards
**docker-compose.yaml**
```
version: '3.9'

services:
  postgresql-postgis:
    build: ./postgresql-postgis
    image: image-postgresql-postgis-eb:v.1.0
    container_name: container-postgresql-postgis-eb
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: ./volumes/data-postgresql
        target: /var/lib/postgresql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "jug735dgdj2372h"
      POSTGRES_DB: "tabellapostgres"
      ALLOW_IP_RANGE: "0.0.0.0/0"
    restart: always
    networks:
      - eb

  pgadmin:
    ...

  java:
    ...

networks:
  eb:
```
**Dockerfile**
```
FROM kartoza/postgis:14-3.2--v2022.05.09
EXPOSE 5432
```
