### ISSUE TITLE
Error creating extensions when more than one database

### ISSUE THREAD

**Issue by bobeal** [kartoza/docker-postgis#406]
Hi,

I have a setup where I create two databases and load multiple extensions:

```
  postgres:
    image: kartoza/postgis:15-3.3
    environment:
      - POSTGRES_DBNAME=db1,db2
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,timescaledb,pgcrypto
      - [other environment variables]
    [other config like ports and volume]
```

The creation of the extensions goes well for the 1st DB in the list. However, for the second DB, it seems like the parsing of the extensions fails somewhere and the following command is issued instead (which of course fails):

```sql
CREATE EXTENSION IF NOT EXISTS postgis timescaledb pgcrypto cascade;
```

Tried to find the origin of the problem in `setup-database.sh` and in the new `extension_install` function in `env-data.sh` but found nothing obvious (for me, my shell knowledge is quite limited...).
