### ISSUE TITLE
docker-compose usage with persistent data, database exited with code 1

### ISSUE THREAD

**Issue by euqip** [kartoza/docker-postgis#41]
Hi Tim, thanks for the great job.

I tried to use the Postgis database container together with Qgis 2.14 container. Both separately worked fine.
I bundled all in a docker-compose.yml file, using persistent postgres data on local drive.
Here is my docker-compose.yml file:

``` yaml
version: '2'
services:
  qgis:
    image: "kartoza/qgis-desktop:2.14"
    environment:
      - DISPLAY=unix$DISPLAY
    volumes:
      - ${HOME}:/home/${USER}
      - /tmp/.X11-unix:/tmp/.X11-unix
    links :
      - db:db

  db:
    image: "kartoza/postgis:9.4-2.1"
    ports:
      - 25432:5432
    volumes:
      - /Docker/data/postgres_postgis/:/var/lib/postgresql
      - /Docker/data/postgis/pg_hba.conf:/etc/postgresql/9.4/main/pg_hba.conf
```

By doing this way, I do not need database container IP address to call it, I simply use db.
(/Docker is a drive dedicated to docker images)

When stopping both containers, the postmaster.pid is never reset.  It makes the database container refusing to start next time even if I delete the file.  The postmaster.pid file is contained in the persistent data directory, in 'main' folder.

The error message:

``` vim
db_1    | 2016-04-26 16:15:17 UTC [63-1] FATAL:  pre-existing shared memory block (key 5432001, ID 32768) is still in use
db_1    | 2016-04-26 16:15:17 UTC [63-2] HINT:  If you're sure there are no old server processes still running, remove the shared memory block or just delete the file "postmaster.pid".
214_db_1 exited with code 1
```

The second persistent data is the pg_hba.conf file, a copy of the original, with 1 more line to enable qgis container IP range. (mine is 172.21.0.0/16)  This file is normally adjusted at startup with startup.sh where IP 172.17.0.0/16 is hard coded and apended to the pg_hda.conf file.  Do you think it is possible to read server IP and reuse it? I tried ifconfig but did'nt work within container.
