### ISSUE TITLE
postgres@postgres FATAL:  Peer authentication failed for user "postgres"

### ISSUE THREAD

**Issue by cecililu** [kartoza/docker-postgis#446]
### What is the bug or the crash?

real-db-1      | 2023-09-06 13:41:44.745 UTC [299] postgres@postgres LOG:  provided user name (postgres) and authenticated user name (root) do not match
real-db-1      | 2023-09-06 13:41:44.745 UTC [299] postgres@postgres FATAL:  Peer authentication failed for user "postgres"
real-db-1      | 2023-09-06 13:41:44.745 UTC [299] postgres@postgres DETAIL:  Connection matched pg_hba.conf line 90: "local   all             postgres      peer"

### Steps to reproduce the issue

```
db:
    image: kartoza/postgis:15-3.4
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .db_env
    networks:
      - test_nw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
```
where .db_env
```
POSTGRES_USER=postgres
POSTGRES_DB=ag_db
POSTGRES_PASS=postgres
PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
PGADMIN_DEFAULT_PASSWORD=root
ALLOW_IP_RANGE=0.0.0.0/0
RUN_AS_ROOT=false
POSTGRES_UID=1000
POSTGRES_GID=1000
USER=postgresuser
GROUP_NAME=postgresusers
MONGO_INITDB_ROOT_USERNAME=root
MONGO_INITDB_ROOT_PASSWORD=root
```

### Versions

`kartoza/postgis:15-3.4`

### Additional context

Seems to show that error even though works fine. Also can i not use bind mount instead of volume mount?When i compose down and up data seems to be gone.Does making bind mount not persist data as above

**Comment by NyakudyaA** [comment]
Generally it's not recommended to set a user as postgres, there is already a super user account for that. We might even prevent this specific username in future.

Try using `foo` or something different

**Comment by rimvislt** [comment]
Same issue can not login into database with docker user from any other docker services or outside. Is is something specific with release number?

docker compose.yml
```
services:
  db:
    image: kartoza/postgis:9.6-2.4
    volumes:
      - postgis-data:/var/lib/postgresql
      - dbbackups:/backups
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
      - RUN_AS_ROOT=true
    ports:
      - "25432:5432"
    healthcheck:
      test: "PGPASSWORD=docker pg_isready -h 127.0.0.1 -U docker -d gis"

volumes:
  dbbackups:
  postgis-data:
```
```
docker compose exec db psql --username=docker --password --dbname=gis
Password for user docker: 
psql: FATAL:  Peer authentication failed for user "docker"
```
---


```
xx-db-1   | /docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
xx-db-1   | 
xx-db-1   | Postgres initialisation process completed .... restarting in foreground
xx-db-1   | 2023-10-17 15:00:46.523 UTC [119] LOG:  database system was shut down at 2023-10-17 15:00:45 UTC
xx-db-1   | 2023-10-17 15:00:46.526 UTC [119] LOG:  MultiXact member wraparound protections are now enabled
xx-db-1   | 2023-10-17 15:00:46.530 UTC [123] LOG:  autovacuum launcher started
xx-db-1   | 2023-10-17 15:00:46.530 UTC [117] LOG:  database system is ready to accept connections
xx-db-1   | 2023-10-17 15:00:53.241 UTC [138] docker@gis LOG:  provided user name (docker) and authenticated user name (root) do not match
xx-db-1   | 2023-10-17 15:00:53.241 UTC [138] docker@gis FATAL:  Peer authentication failed for user "docker"
xx-db-1   | 2023-10-17 15:00:53.241 UTC [138] docker@gis DETAIL:  Connection matched pg_hba.conf line 90: "local   all             all                                     peer"
```
