### ISSUE TITLE
Not accepting environment from docker-compsoe file

### ISSUE THREAD

**Issue by egistic** [kartoza/docker-postgis#462]
### What is the bug or the crash?

db_default_kartoza_1  | 2023-11-06 10:39:26.291 UTC [72] FATAL:  "min_wal_size" must be at least twice "wal_segment_size"
db_default_kartoza_1  | 2023-11-06 10:39:26.291 UTC [72] LOG:  database system is shut down

### Steps to reproduce the issue

Docker-compose file:
```
version: "3"
services:
  db_default_kartoza:
    image: "kartoza/postgis:latest"
    volumes:
      - "postgis_kartoza:/var/lib/postgresql"
      - "./dbbackups:/backups"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file:
      - parameters.env
    command: echo  $TEST
volumes:
  postgis_kartoza:
    external: true
```

parameters.env file:

`POSTGRES_DBNAME=test
POSTGRES_USER=docker
POSTGRES_PASS=123456
ALLOW_IP_RANGE=0.0.0.0/0
POSTGRES_MULTIPLE_EXTENSIONS=hstore,postgis_topology,postgis_raster,pgrouting
EXTRA_CONF=max_connections=500
WAL_SIZE=4GB
MIN_WAL_SIZE=2GB
WAL_SEGSIZE=128
MAINTAINANCE_WORK_MEM=1GB
SHARED_BUFFERS=2GB
WORK_MEM=32MB
WAL_BUFFERS=4MB
RUN_AS_ROOT=true
TEST= TEST1`

### Versions

Postgresql 16

**Comment by eriktelepovsky** [comment]
I have same issue:

```
version: '3.9'

services:
  db:
    image: kartoza/postgis:15-3.4
    environment:
      WAL_SIZE: '4GB'
      MIN_WAL_SIZE: '2048MB'
      WAL_SEGSIZE: '1024'
```

Logs:
```
2024-03-02 21:56:41.037 UTC [125] FATAL:  "min_wal_size" must be at least twice "wal_segment_size"
2024-03-02 21:56:41.038 UTC [125] LOG:  database system is shut down
```
