### ISSUE TITLE
can't access with psql when using docker-compose

### ISSUE THREAD

**Issue by scizmeli** [kartoza/docker-postgis#74]
I am able to launch and access psql database with persistent local storage with 

`sudo docker run --name=postgiscontainer -d -e POSTGRES_USER=knn -e POSTGRES_PASS=knn -e POSTGRES_DBNAME=knn -e ALLOW_IP_RANGE=0.0.0.0/0 -p 54322:5432 -v $(pwd)/postgres_data:/var/lib/postgresql --restart=always kartoza/postgis:9.6-2.4`

I can connect to the database from the host
`PGPASSWORD=knn psql -U knn -h localhost -p 54322 knn`

```
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

knn=#

```
So far so good. But since I want this a part of a more complex system, I would like to launch the container with docker-compose. Here is my docker-compose.yml
```
version: "3"
services:
  postgis:
    image: kartoza/postgis:9.6-2.4
    ports:
      - "54322:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=knn
      - POSTGRES_PASSWD=knn
      - POSTGRES_DBNAME=knn
      - ALLOW_IP_RANGE=0.0.0.0/0
volumes:
  db-data:
```
I launch the container as microservice
`sudo docker-compose -f docker-compose.example.yml up -d
Starting postgis_postgis_1 ... 
Starting postgis_postgis_1 ... done
`

Now I want to connect again to the database from the host
`PGPASSWORD=knn psql -U knn -h localhost -p 54322 knn
`

But this time I cant login to the database
```
psql: FATAL:  password authentication failed for user "knn"
FATAL:  password authentication failed for user "knn
```

To verify if the parameters I passed are in the container's environment, I enter inside the container and check the environment
```
sudo docker exec -i -t 25b78fcb49eb /bin/bash
# env

```
and obtain 

```
POSTGRES_PASSWD=knn
HOSTNAME=25b78fcb49eb
PWD=/
HOME=/root
POSTGRES_DBNAME=knn
DEBIAN_FRONTEND=noninteractive
TERM=xterm
POSTGRES_USER=knn
SHLVL=1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ALLOW_IP_RANGE=0.0.0.0/0
_=/usr/bin/env
```

I see the login credentials are correctly passed into the container's environment but are not considered by postgresql. I am stuck and at loss. Where am I doing wrong?

thanks for your help
