### ISSUE TITLE
Issue connecting to database from docker host and other containers on macOS

### ISSUE THREAD

**Issue by adamoxley** [kartoza/docker-postgis#83]
Currently seeing an error when trying to connect to the Postgres container either from host machine or other docker containers on macOS High Sierra, Docker Version 17.12.0-ce-mac49 (21995).

Error I get is- 
> docker@gis FATAL:  no pg_hba.conf entry for host "172.19.0.1", user "docker", database "gis", SSL off

I assumed this was due to it defaulting (as the docs specify) to the docker private subnet. So I placed the below into my docker-compose file

```
postgres:
      image: kartoza/postgis
      environment:
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASS}
        - ALLOW_IP_RANGE=${ALLOW_IP_RANGE}
      ports:
        - "5432:5432"
```

With the follow `.env` file -

```
DB_NAME=gis
DB_USER=docker
DB_PASS=docker
DB_PORT=5432
ALLOW_IP_RANGE='0.0.0.0/0'
```

(Also tried with `ALLOW_IP_RANGE=0.0.0.0/0`, as well as hardcoding rather than env variables)

Still, no luck and I couldn't connect. I decided to try out manually adding `0.0.0.0/0` to `pg_hba.conf` by running the following (note that `65e35bba325d` is the container ID of the postgres container) -

```
docker exec -it 65e35bba325d bash
root@65e35bba325d:~# sed -i '$ a\host all all 0.0.0.0/0 md5' /etc/postgresql/10/main/pg_hba.conf
root@65e35bba325d:~# /etc/init.d/postgresql reload
```

This lets me successfully connect to the database from both my other containers and my host.

Not entirely sure if I am doing something wrong here in applying the allowed IP range, but I couldn't get it applying via docker compose. Any help would be great.

Thanks!
