### ISSUE TITLE
/start-postgis.sh: line 74: /etc/postgresql/10.0/main/pg_hba.conf: No such file or directory

### ISSUE THREAD

**Issue by lomasz** [kartoza/docker-postgis#84]
I've downloaded newest version (created one hour ago) of 10.0-2.4 from dockerhub, but during running container `start-postgis.sh` is still trying to update `pg_hba.conf` in `/etc/postgresql/10.0/main/` instead of `/etc/postgresql/10/main/`
```
 echo "host    all             all             $ALLOW_IP_RANGE              md5" >> /etc/postgresql/10.0/main/pg_hba.conf`
```
so when I try to run my application using `docker-compose` I can not connect to database - I can connect to database only using host `localhost`.

My `docker-compose`:
```
version: '3.3'

services:
  db:
    image: kartoza/postgis:10.0-2.4
    ports:
      - "5432:5432"
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
  app:
    build: .
    ports:
      - "4326:4326"
    links:
      - "db"
    environment:
       SPRING_PROFILES_ACTIVE: docker
    command: ["/wait-for-it.sh", "-h", "db", "-p", "5432", "-t", "30", "-s", "--", "java", "-jar", "/app.jar"]
```
