### ISSUE TITLE
ALLOWED_HOSTS is not recognized in latest (10.0-2.4)

### ISSUE THREAD

**Issue by synchrone** [kartoza/docker-postgis#85]
When ALLOWED_HOSTS is specified (0.0.0.0/0 in my case), the container starts with a line:
`/start-postgis.sh: line 74: /etc/postgresql/10.0/main/pg_hba.conf: No such file or directory`

and then
`2018-03-12 10:40:13.095 UTC [144] docker@gis FATAL:  no pg_hba.conf entry for host "172.20.0.4", user "docker", database "gis", SSL on`

This does not happen in 9.6-2.4

**Comment by jancelin** [comment]
https://github.com/kartoza/docker-postgis/pull/88

**Comment by timlinux** [comment]
Can you test again? I just merged a bunch of changes to develop and 10 branch - it should work now.

**Comment by jancelin** [comment]
OK for me,
nice commit and nice restructuring of the setup.
I also needed to restore a dump at boot time, I added this to the setup-database.sh 
```
su - postgres -c " psql $POSTGRES_DBNAME -f /home/$POSTGRES_DUMP "
```
and this is the docker-compose.yml
```
version: "3.3"
services:
  postgis:
    image: kartoza/postgis:10.0-2.4
    ports:
      - 5432:5432
    entrypoint: >
      bash -c "wget -N -P / https://raw.githubusercontent.com/jancelin/docker-postgis/master/setup-database.sh &&
               wget -N -P /home https://github.com/jancelin/docker-postgis/raw/master/geopoppy.sql &&
               /docker-entrypoint.sh"
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_USER=docker
      - POSTGRES_DBNAME=geopoppy
      - POSTGRES_DUMP=geopoppy.sql
```
The sources are there:
https://github.com/jancelin/docker-postgis

with the possibility to Play with Docker:
[![Try in PWD](https://cdn.rawgit.com/play-with-docker/stacks/cff22438/assets/images/button.png)](http://play-with-docker.com?stack=https://raw.githubusercontent.com/jancelin/docker-lizmap/3.1.11/docker-compose.yml)
